import { useState } from 'react'
import { useParams } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { pitchApi } from '@/api'
import { Button, InlineError, SkeletonCard, EmptyState } from '@/components/ui'

export function PitchPage() {
  const { projectId } = useParams<{ projectId: string }>()
  const [generating, setGenerating] = useState(false)
  const [genError, setGenError] = useState<string | null>(null)

  const { data, isLoading, error, refetch } = useQuery({
    queryKey: ['pitch', projectId],
    queryFn: () => pitchApi.get(projectId!),
    enabled: !!projectId,
    retry: false,
  })

  const handleGenerate = async () => {
    if (!projectId) return
    setGenerating(true)
    setGenError(null)
    try {
      await pitchApi.generate(projectId)
      await refetch()
    } catch (e: any) {
      if (e.status === 409) setGenError('Roadmap not far enough along yet — complete more tasks first.')
      else setGenError(e.message ?? 'Generation failed')
    } finally {
      setGenerating(false)
    }
  }

  const handleExport = () => {
    if (!data?.pitch_outline) return
    const p = data.pitch_outline
    const text = [
      '# Hackathon Pitch\n',
      `## Problem\n${p.problem}\n`,
      `## Solution\n${p.solution}\n`,
      `## Demo Flow\n${p.demo_flow.map((s, i) => `${i + 1}. ${s}`).join('\n')}\n`,
      `## Differentiator\n${p.differentiator}\n`,
      data.generated_at ? `\n_Generated: ${new Date(data.generated_at).toLocaleString()}_` : '',
    ].join('\n')

    const blob = new Blob([text], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'pitch-outline.md'
    a.click()
    URL.revokeObjectURL(url)
  }

  if (isLoading) return <div className="space-y-4"><SkeletonCard /><SkeletonCard /></div>

  const pitch = data?.pitch_outline

  return (
    <div className="max-w-2xl space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between gap-3">
        <div>
          <h1 className="text-xl font-800 text-navy">Pitch Outline</h1>
          <p className="text-sm text-muted mt-0.5">
            {data?.generated_at
              ? `Generated ${new Date(data.generated_at).toLocaleString()}`
              : 'Generated by the Pitch Agent'}
          </p>
        </div>
        <div className="flex items-center gap-2">
          {pitch && (
            <Button variant="secondary" size="sm" onClick={handleExport}>
              Download .md
            </Button>
          )}
          <Button size="sm" onClick={handleGenerate} loading={generating}>
            {pitch ? 'Regenerate' : 'Generate pitch'}
          </Button>
        </div>
      </div>

      <InlineError message={genError} />

      {/* Pitch content */}
      {!pitch ? (
        <EmptyState
          icon="🎤"
          title="No pitch generated yet"
          description="The Pitch Agent auto-triggers when your roadmap is mostly complete. Or generate it now."
          action={
            <Button onClick={handleGenerate} loading={generating}>
              Generate pitch
            </Button>
          }
        />
      ) : (
        <div className="space-y-4">
          {/* Problem */}
          <div className="bg-white border border-border rounded-card shadow-card p-5">
            <div className="flex items-center gap-2 mb-3">
              <span className="text-base">🎯</span>
              <p className="text-[10px] font-700 uppercase tracking-wider text-muted-2">Problem</p>
            </div>
            <p className="text-base font-600 text-navy leading-relaxed">{pitch.problem}</p>
          </div>

          {/* Solution */}
          <div className="bg-white border border-border rounded-card shadow-card p-5">
            <div className="flex items-center gap-2 mb-3">
              <span className="text-base">💡</span>
              <p className="text-[10px] font-700 uppercase tracking-wider text-muted-2">Solution</p>
            </div>
            <p className="text-base font-600 text-navy leading-relaxed">{pitch.solution}</p>
          </div>

          {/* Demo flow */}
          {pitch.demo_flow?.length > 0 && (
            <div className="bg-white border border-border rounded-card shadow-card p-5">
              <div className="flex items-center gap-2 mb-3">
                <span className="text-base">🎬</span>
                <p className="text-[10px] font-700 uppercase tracking-wider text-muted-2">Demo flow</p>
              </div>
              <ol className="space-y-2.5">
                {pitch.demo_flow.map((step, i) => (
                  <li key={i} className="flex items-start gap-3">
                    <span className="w-6 h-6 rounded-[7px] bg-primary-soft text-primary-dark text-xs font-800 flex items-center justify-center flex-none mt-0.5">
                      {i + 1}
                    </span>
                    <p className="text-sm text-navy leading-relaxed">{step}</p>
                  </li>
                ))}
              </ol>
            </div>
          )}

          {/* Differentiator */}
          <div className="bg-gradient-to-br from-primary-soft to-white border border-orange-200 rounded-card shadow-card p-5">
            <div className="flex items-center gap-2 mb-3">
              <span className="text-base">⚡</span>
              <p className="text-[10px] font-700 uppercase tracking-wider text-primary-dark/70">Why us</p>
            </div>
            <p className="text-base font-700 text-primary-dark leading-relaxed">{pitch.differentiator}</p>
          </div>
        </div>
      )}
    </div>
  )
}
