import { useEffect, useRef, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { plannerApi } from '@/api'
import { PlanView } from '@/components/plan/PlanView'
import type { ScopeData, RoadmapTask } from '@/types'

function isEmptyDraft(scope: ScopeData | undefined, roadmap: RoadmapTask[] | undefined) {
  return (
    !scope ||
    ((scope.mvp_features ?? []).length === 0 &&
      (scope.cut_features ?? []).length === 0 &&
      (scope.assumptions ?? []).length === 0) ||
    (roadmap ?? []).length === 0
  )
}

// Planner flow maps to the backend v1 surface:
// GET /plan/draft reads the persisted draft; POST /plan/chat is what
// actually runs the Scope Critic + Planner to produce/refine it. If the
// stored draft is still empty (the project just finished ingestion), we
// auto-send one opening chat turn so the plan actually appears.
export function PlanPage() {
  const { projectId } = useParams<{ projectId: string }>()
  const navigate = useNavigate()
  const queryClient = useQueryClient()
  const [feedback, setFeedback] = useState('')
  const [lastReply, setLastReply] = useState<string | null>(null)
  const [current, setCurrent] = useState<{
    scope: ScopeData
    roadmap: RoadmapTask[]
  } | null>(null)
  const autoGenerated = useRef(false)

  const { data: draft, isLoading, isError } = useQuery({
    queryKey: ['plan-draft', projectId],
    queryFn: () => plannerApi.draft(projectId!),
    enabled: !!projectId,
  })

  useEffect(() => {
    if (draft) {
      setCurrent({ scope: draft.draft_scope, roadmap: draft.draft_roadmap })
    }
  }, [draft])

  const generateFirstDraft = useMutation({
    mutationFn: () =>
      plannerApi.feedback(projectId!, {
        message: 'Create the plan for this project now.',
      }),
    onSuccess: (res) => {
      autoGenerated.current = true
      setCurrent({ scope: res.draft_scope, roadmap: res.draft_roadmap })
      setLastReply(res.reply)
      queryClient.invalidateQueries({ queryKey: ['plan-draft', projectId] })
    },
  })

  // Auto-generate the first draft when the stored one is empty.
  useEffect(() => {
    if (!draft || autoGenerated.current) return
    if (isEmptyDraft(draft.draft_scope, draft.draft_roadmap)) {
      autoGenerated.current = true
      generateFirstDraft.mutate()
    }
  }, [draft, generateFirstDraft])

  const sendFeedback = useMutation({
    mutationFn: () => plannerApi.feedback(projectId!, { message: feedback }),
    onSuccess: (res) => {
      setCurrent({ scope: res.draft_scope, roadmap: res.draft_roadmap })
      setLastReply(res.reply)
      setFeedback('')
      queryClient.invalidateQueries({ queryKey: ['plan-draft', projectId] })
    },
  })

  const approve = useMutation({
    mutationFn: () => plannerApi.approve(projectId!),
    onSuccess: () => {
      navigate(`/projects/${projectId}/dashboard`)
    },
  })

  if (isError) {
    return (
      <div className="mx-auto max-w-3xl p-8">
        <p className="text-sm text-muted">Couldn't load the plan draft.</p>
      </div>
    )
  }

  if (isLoading || !current || generateFirstDraft.isPending) {
    return (
      <div className="flex h-screen items-center justify-center bg-bg">
        <div className="text-center">
          <div className="skeleton mx-auto h-8 w-48" />
          <p className="mt-4 text-sm text-muted">Drafting your plan…</p>
        </div>
      </div>
    )
  }

  const hasPlan = !isEmptyDraft(current.scope, current.roadmap)

  return (
    <div className="mx-auto max-w-3xl p-8">
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h1 className="text-lg font-semibold text-text">Plan</h1>
          <p className="text-sm text-muted">Give feedback to refine, or approve when it looks right.</p>
        </div>
        <button
          onClick={() => approve.mutate()}
          disabled={!hasPlan || approve.isPending}
          className="rounded-lg bg-success px-4 py-2 text-sm font-medium text-white disabled:opacity-40"
        >
          {approve.isPending ? 'Approving…' : 'Approve plan'}
        </button>
      </div>

      {lastReply && (
        <p className="mb-4 rounded-lg border border-border bg-card p-3 text-sm text-text">{lastReply}</p>
      )}

      {generateFirstDraft.error && (
        <p className="mb-4 rounded-lg border border-danger/30 bg-danger-soft p-3 text-sm text-danger">
          Couldn't generate the plan: {generateFirstDraft.error.message}
        </p>
      )}

      <div className="rounded-card border border-border bg-card p-5 shadow-card">
        <PlanView scope={current.scope} roadmap={current.roadmap} />
      </div>

      <form
        onSubmit={(e) => {
          e.preventDefault()
          if (feedback.trim()) sendFeedback.mutate()
        }}
        className="mt-6 flex gap-2"
      >
        <input
          value={feedback}
          onChange={(e) => setFeedback(e.target.value)}
          placeholder="e.g. Cut the notifications feature, add more buffer to day 2…"
          className="flex-1 rounded-lg border border-border px-3 py-2 text-sm outline-none focus:border-primary"
        />
        <button
          type="submit"
          disabled={sendFeedback.isPending || !feedback.trim()}
          className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white disabled:opacity-50"
        >
          {sendFeedback.isPending ? 'Revising…' : 'Send feedback'}
        </button>
      </form>
    </div>
  )
}
