import { useEffect, useRef, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { plannerApi } from '@/api'
import { PlanView } from '@/components/plan/PlanView'
import type { ScopeData, RoadmapTask } from '@/types'

function isEmptyDraft(scope: ScopeData | undefined, roadmap: RoadmapTask[] | undefined) {
  return (
    !scope ||
    ((scope.mvp_features ?? []).length === 0 &&
      (scope.cut_features ?? []).length === 0 &&
      (scope.assumptions ?? []).length === 0) ||
    (roadmap ?? []).length === 0
  )
}

// Planner flow maps to the backend v1 surface:
// GET /plan/draft reads the persisted draft; POST /plan/chat is what
// actually runs the Scope Critic + Planner to produce/refine it. If the
// stored draft is still empty (the project just finished ingestion), we
// auto-send one opening chat turn so the plan actually appears.
export function PlanPage() {
  const { projectId } = useParams<{ projectId: string }>()
  const navigate = useNavigate()
  const queryClient = useQueryClient()
  const [feedback, setFeedback] = useState('')
  const [lastReply, setLastReply] = useState<string | null>(null)
  const [generationError, setGenerationError] = useState<string | null>(null)
  const [current, setCurrent] = useState<{
    scope: ScopeData
    roadmap: RoadmapTask[]
  } | null>(null)
  const autoGenerated = useRef(false)

  const { data: draft, isLoading, isError, refetch: refetchDraft } = useQuery({
    queryKey: ['plan-draft', projectId],
    queryFn: () => plannerApi.draft(projectId!),
    enabled: !!projectId,
  })

  useEffect(() => {
    if (draft) {
      setCurrent({ scope: draft.draft_scope, roadmap: draft.draft_roadmap })
    }
  }, [draft])

  const generateFirstDraft = useMutation({
    mutationFn: () =>
      plannerApi.feedback(projectId!, {
        message: 'Create the plan for this project now.',
      }),
    onSuccess: (res) => {
      autoGenerated.current = true
      setGenerationError(null)
      if (isEmptyDraft(res.draft_scope, res.draft_roadmap)) {
        setGenerationError('Planner returned an empty plan. Click retry to try generating again.')
      } else {
        setCurrent({ scope: res.draft_scope, roadmap: res.draft_roadmap })
      }
      setLastReply(res.reply)
      queryClient.invalidateQueries({ queryKey: ['plan-draft', projectId] })
    },
    onError: (err: Error) => {
      setGenerationError(err.message || 'Failed to generate plan.')
    },
  })

  // Auto-generate the first draft when the stored one is empty.
  useEffect(() => {
    if (!draft || autoGenerated.current) return
    if (isEmptyDraft(draft.draft_scope, draft.draft_roadmap)) {
      autoGenerated.current = true
      generateFirstDraft.mutate()
    }
  }, [draft])

  const sendFeedback = useMutation({
    mutationFn: () => plannerApi.feedback(projectId!, { message: feedback }),
    onSuccess: (res) => {
      setGenerationError(null)
      if (isEmptyDraft(res.draft_scope, res.draft_roadmap)) {
        setGenerationError('Plan update produced an empty plan. Retrying generation recommended.')
      } else {
        setCurrent({ scope: res.draft_scope, roadmap: res.draft_roadmap })
      }
      setLastReply(res.reply)
      setFeedback('')
      queryClient.invalidateQueries({ queryKey: ['plan-draft', projectId] })
    },
    onError: (err: Error) => {
      setGenerationError(err.message || 'Failed to update plan.')
    },
  })

  const approve = useMutation({
    mutationFn: () => plannerApi.approve(projectId!),
    onSuccess: () => {
      navigate(`/projects/${projectId}/dashboard`)
    },
  })

  if (isError) {
    return (
      <div className="mx-auto max-w-3xl p-8">
        <p className="text-sm text-red-500">Couldn't load the plan draft.</p>
        <button
          onClick={() => refetchDraft()}
          className="mt-4 rounded-lg bg-primary px-4 py-2 text-sm text-white"
        >
          Retry Loading
        </button>
      </div>
    )
  }

  if (isLoading || generateFirstDraft.isPending) {
    return (
      <div className="flex h-screen items-center justify-center bg-bg">
        <div className="text-center">
          <div className="skeleton mx-auto h-8 w-48" />
          <p className="mt-4 text-sm text-muted">Drafting your plan…</p>
        </div>
      </div>
    )
  }

  const hasValidPlan = current && !isEmptyDraft(current.scope, current.roadmap)

  return (
    <div className="mx-auto max-w-3xl p-8">
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h1 className="text-lg font-semibold text-text">Plan</h1>
          <p className="text-sm text-muted">Give feedback to refine, or approve when it looks right.</p>
        </div>
        <button
          onClick={() => approve.mutate()}
          disabled={!hasValidPlan || approve.isPending}
          className="rounded-lg bg-success px-4 py-2 text-sm font-medium text-white disabled:opacity-40"
        >
          {approve.isPending ? 'Approving…' : 'Approve plan'}
        </button>
      </div>

      {lastReply && (
        <p className="mb-4 rounded-lg border border-border bg-card p-3 text-sm text-text">{lastReply}</p>
      )}

      {(generationError || generateFirstDraft.error || sendFeedback.error) && (
        <div className="mb-4 flex items-center justify-between rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-500">
          <span>
            {generationError ||
              generateFirstDraft.error?.message ||
              sendFeedback.error?.message}
          </span>
          <button
            onClick={() => generateFirstDraft.mutate()}
            disabled={generateFirstDraft.isPending}
            className="rounded bg-red-500 px-3 py-1 text-xs text-white hover:bg-red-600"
          >
            {generateFirstDraft.isPending ? 'Generating…' : 'Retry generation'}
          </button>
        </div>
      )}

      {!hasValidPlan && !generateFirstDraft.isPending && (
        <div className="mb-6 flex flex-col items-center justify-center rounded-card border border-dashed border-border bg-card p-8 text-center">
          <p className="mb-4 text-sm text-muted">No valid plan generated yet.</p>
          <button
            onClick={() => generateFirstDraft.mutate()}
            disabled={generateFirstDraft.isPending}
            className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white disabled:opacity-50"
          >
            Generate plan
          </button>
        </div>
      )}

      {hasValidPlan && (
        <div className="rounded-card border border-border bg-card p-5 shadow-card">
          <PlanView scope={current.scope} roadmap={current.roadmap} />
        </div>
      )}

      <form
        onSubmit={(e) => {
          e.preventDefault()
          if (feedback.trim()) sendFeedback.mutate()
        }}
        className="mt-6 flex gap-2"
      >
        <input
          value={feedback}
          onChange={(e) => setFeedback(e.target.value)}
          placeholder="e.g. Cut the notifications feature, add more buffer to day 2…"
          className="flex-1 rounded-lg border border-border px-3 py-2 text-sm outline-none focus:border-primary"
        />
        <button
          type="submit"
          disabled={sendFeedback.isPending || !feedback.trim()}
          className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white disabled:opacity-50"
        >
          {sendFeedback.isPending ? 'Revising…' : 'Send feedback'}
        </button>
      </form>
    </div>
  )
}

